command_dict = {
    "Reaction Control Subsystem": {
        "Code": "RCS",
        "Commands": {"CMD01":['THRUST_X', range(0,60)],
                     "CMD02":['THRUST_Y', range(0,60)],
                     "CMD03":['THRUST_Z', range(0,60)],
                     "CMD04":['SAFE_MODE', {0, 1}]}
    },
    "Thermal Control Subsystem": {
        "Code": "TCS",
        "Commands": {"CMD01":['HEATER_ON', {0, 1}],
                     "CMD02":['HEATER_OFF', {0, 1}],
                     "CMD03":['VENT_OPEN_RADIATOR', {0, 1}],
                     "CMD04":['TEMP_SETPOINT', range(-30,60)]}
    },
    "Attitude Control Subsystem": {
        "Code": "ACS",
        "Commands": {"CMD01":['ROTATE_X', range(-360,360)],
                     "CMD02":['ROTATE_Y', range(-360,360)],
                     "CMD03":['ROTATE_Z', range(-360,360)],
                     "CMD04":['SAFE_MODE', {0, 1}]}
    },
    "Command & Data Handling": {
        "Code": "CDH",
        "Commands": {"CMD01":['TRANSMIT_HIGH', {0, 1}],
                     "CMD02":['TRANSMIT_LOW', {0, 1}],
                     "CMD03":['RECEIVE_MODE',{0, 1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    },
    "Telemetry, Tracking, & Command": {
        "Code": "TTC",
        "Commands": {"CMD01":['TRANSMIT_MODE', {0,1}],
                     "CMD02":['RECEIVE_MODE', {0,1}],
                     "CMD03":['TRACKING_MODE', {0,1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    },
    "Electrical Power Subsystem": {
        "Code": "EPS",
        "Commands": {"CMD01":['BATTERY_CHARGE_MODE', {0,1}],
                     "CMD02":['POWER_ON_MODULE', {0,1,2,3,4}],
                     "CMD03":['POWER_OFF_MODULE', {0,1,2,3,4}],
                     "CMD04":['VOLTAGE_SETPOINT', range(0,120)]}
    },
    "Payload System 1": {
        "Code": "PL1",
        "Commands": {"CMD01":['START_DATA_ACQUISITION', {0,1}],
                     "CMD02":['STOP_DATA_ACQUISITION', {0,1}],
                     "CMD03":['CALIBRATE_SENSOR', {0,1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    },
    "Payload System 2": {
        "Code": "PL2",
        "Commands": {"CMD01":['START_DATA_ACQUISITION', {0,1}],
                     "CMD02":['STOP_DATA_ACQUISITION', {0,1}],
                     "CMD03":['CALIBRATE_SENSOR', {0,1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    }
}

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 15 18:02:11 2024

@author: alexanderbeyrooty
"""
def parse_command(command):
    """ This function was adapted from suggestions generated by CHATGPT """
    """
    Parse a command string based on the formatted schema.
    :param command: String command in the format "SUB:CMDxx:parameter"
    :return: Tuple (subsystem_name, command_description, parameter_value) or error message
    """
    subsystems = {
        "RCS": "Reaction Control Subsystem",
        "TCS": "Thermal Control Subsystem",
        "ACS": "Attitude Control Subsystem",
        "EPS": "Electrical Power Subsystem",
        "CDH": "Command & Data Handling",
        "TTC": "Telemetry, Tracking, & Command",
        "PL1": "Payload System 1",
        "PL2": "Payload System 2"
    }

    commands = {
        "CMD01": "THRUST X",
        "CMD02": "THRUST Y",
        "CMD03": "THRUST Z",
        "CMD04": "SAFE MODE"
    }

    try:
        # Split the command into its components
        parts = command.split(":")
        if len(parts) != 3:
            raise ValueError("Invalid command format. Must be 'SUB:CMDxx:parameter'.")

        subsystem_code, command_code, parameter = parts
        subsystem_name = subsystems.get(subsystem_code, "Unknown Subsystem")
        command_description = commands.get(command_code, "Unknown Command")
        parameter_value = float(parameter)

        return subsystem_name, command_description, parameter_value

    except ValueError as e:
        return f"Error parsing command: {e}"

# Example usage
command = "RCS:CMD01:10"
result = parse_command(command)
print(result)

def parse_and_validate_command(command, command_ranges):
    """
    Parse a command and validate the parameter against acceptable ranges.
    :param command: String command in the format "SUB:CMDxx:parameter"
    :param command_ranges: Dictionary with command ranges for validation
    :return: Tuple (subsystem_name, command_description, parameter_value) or error message
    """
    subsystems = {
        "RCS": "Reaction Control Subsystem",
        "TCS": "Thermal Control Subsystem",
        "ACS": "Attitude Control Subsystem",
        "EPS": "Electrical Power Subsystem",
        "CDH": "Command & Data Handling",
        "TTC": "Telemetry, Tracking, & Command",
        "PL1": "Payload System 1",
        "PL2": "Payload System 2"
    }

    commands = {
        "CMD01": "THRUST X",
        "CMD02": "THRUST Y",
        "CMD03": "THRUST Z",
        "CMD04": "SAFE MODE"
    }

    try:
        # Split the command into its components
        parts = command.split(":")
        if len(parts) != 3:
            raise ValueError("Invalid command format. Must be 'SUB:CMDxx:parameter'.")

        subsystem_code, command_code, parameter = parts
        subsystem_name = subsystems.get(subsystem_code, "Unknown Subsystem")
        command_description = commands.get(command_code, "Unknown Command")

        # Convert parameter to float and validate
        parameter_value = float(parameter)
        if command_code in command_ranges:
            min_value, max_value = command_ranges[command_code]
            if not (min_value <= parameter_value <= max_value):
                raise ValueError(
                    f"Parameter {parameter_value} out of range for {command_code} "
                    f"({min_value} - {max_value})."
                )

        return subsystem_name, command_description, parameter_value

    except ValueError as e:
        return f"Error parsing or validating command: {e}"

# Command ranges for validation
command_ranges = {
    "CMD01": (0, 100),  # Example range for THRUST X
    "CMD02": (0, 100),
    "CMD03": (0, 100),
    "CMD04": (-10, 10)  # Example range for SAFE MODE
}

# Example usage
command = "RCS:CMD01:120"  # Invalid parameter
result = parse_and_validate_command(command, command_ranges)
print(result)

commands_to_test = [
    "EPS:CMD01:0",      # Valid command
    "ACS:CMD04:-1",     # Valid but near boundary
    "RCS:INVALID:0",    # Invalid command code
    "RCS:CMD01:150"     # Parameter out of range
]

for cmd in commands_to_test:
    print(parse_and_validate_command(cmd, command_ranges))
